### ISSUE TITLE
control-flow plugin properties configuration

### ISSUE THREAD

**Issue by syafiqFiqq** [thinkWhere/GeoServer-Docker#9]
can i know where to put the configuration for the control flow which is the controlflow.properties file?

**Comment by rightway1** [comment]
The controlflow.properties file should go into the root of the geoserver data_dir directory.  The sample docker-compose.yml file in this repository maps the data_dir directory to an external volume ~/geoserver_data.  This allows the mapping configuration to be saved between restarts of the geoserver docker instance.
If you choose to keep the data_dir within the container, then you should modify the dockerfile to insert the controlflow.properties file into /opt/geoserver/data_dir  within the container.
